name: Build and Push to Amazon ECR

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ ASIAQ3EGQMCEGNVM7N4B }}
        aws-secret-access-key: ${{ yx/6X6JyQUJwmwIl21NPvre1ukPP/eohOSlx2x9j }}
        aws-region: ${{ us-east-1 }}

    - name: Log in to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ 058264150152.dkr.ecr.us-east-1.amazonaws.com/clo835-week3 }}
        ECR_REPOSITORY: ${{ clo835-week3 }}
        IMAGE_TAG: v0.1
      run: |
        docker build -t $ECR_REPOSITORY:$IMAGE_TAG .
        docker tag $ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG


